---
- name: Install epel-repository
  package:
    name: epel-release
    state: present
  when: ansible_pkg_mgr == "yum"
  
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Install passlib library
  package:
    name: python-passlib
    state: present
  when: nginx_basic_auth_user != "" and nginx_basic_auth_pass != ""

- name: Create configuration directories
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    owner: root
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "conf.d"
    - "snippets"

- name: Ensure log directory exist
  file:
    path: "/var/log/nginx"
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755

- name: Install SELinux packages
  package:
    name: "{{ item }}"
    state: present
  when: ansible_selinux == "enforcing" or ansible_selinux == "permissive"
  with_items: "{{ selinux_packages }}"

- name: Set SELinux boolean to allow nginx to set rlimit
  seboolean:
    name: httpd_setrlimit
    state: yes
    persistent: yes
  when: ansible_selinux == "enforcing" or ansible_selinux == "permissive"
