---
- name: Download nginx_exporter from github and compile it locally
  become: no
  shell: "export GOPATH=/tmp/nginx_exporter; go get github.com/discordianfish/nginx_exporter"
  args:
    creates: /tmp/nginx_exporter
  run_once: yes
  delegate_to: localhost

- name: install prometheus exporter
  copy:
    src: /tmp/nginx_exporter/bin/nginx_exporter
    dest: /opt/nginx_exporter
    mode: 0755

- name: create systemd nginx_exporter service file
  template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
  notify:
  - restart metrics service

- name: add metrics site
  template:
    src: nginx-status.conf.j2
    dest: /etc/nginx/conf.d/nginx-status.conf
  notify:
  - restart nginx

- meta: flush_handlers

- name: ensure metrics service is enabled
  service:
    name: nginx_exporter
    enabled: yes
