---
- name: get nginx exporter
  become: no
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.1.0/nginx-prometheus-exporter-0.1.0-linux-amd64.tar.gz
    dest: /tmp/nginx_exporter.tar.gz
    mode: 0775
  run_once: yes
  delegate_to: localhost

- name: extract nginx_exporter
  become: no
  unarchive:
    src: /tmp/nginx_exporter.tar.gz
    dest: /tmp
  run_once: yes
  delegate_to: localhost

- name: install nginx exporter
  copy:
    src: /tmp/nginx-prometheus-exporter/
    dest: /opt/nginx_exporter
    mode: 0755

- name: add metrics site
  template:
    src: nginx-status.conf.j2
    dest: /etc/nginx/conf.d/nginx-status.conf
  notify:
  - restart nginx

- name: create systemd nginx_exporter service file
  template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
  notify:
  - restart metrics service

- name: ensure metrics service is enabled
  service:
    name: nginx_exporter
    enabled: yes
