---
- name: download nginx_exporter from github and compile it locally
  become: no
  shell: "export GOPATH=/tmp/nginx_exporter; go get github.com/nginxinc/nginx-prometheus-exporter"
  args:
    creates: /tmp/nginx_exporter
  run_once: yes
  delegate_to: localhost

- name: check if build_exporter has been build
  become: no
  stat:
    path: /tmp/nginx_exporter/src/github.com/nginxinc/nginx-prometheus-exporter/nginx-prometheus-exporter
  register: result
  run_once: yes
  delegate_to: localhost

- name: build nginx_exporter
  become: no
  shell: "export GOPATH=/tmp/nginx_exporter; make"
  args:
    chdir: /tmp/nginx_exporter/src/github.com/nginxinc/nginx-prometheus-exporter/
  run_once: yes
  delegate_to: localhost
  when: result.stat.exists == False

- name: install prometheus exporter
  copy:
    src: /tmp/nginx_exporter/src/github.com/nginxinc/nginx-prometheus-exporter/nginx-prometheus-exporter
    dest: /opt/nginx_exporter
    mode: 0755

- name: add metrics site
  template:
    src: nginx-status.conf.j2
    dest: /etc/nginx/conf.d/nginx-status.conf
  notify:
  - restart nginx

- name: create systemd nginx_exporter service file
  template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
  notify:
  - restart metrics service

- name: ensure metrics service is enabled
  service:
    name: nginx_exporter
    enabled: yes