---

- name: Check if conf file exists
  stat:
    path: "{{ nginx_conf_dir }}/nginx.conf"
  register: st
  failed_when: st.stat.exists != True

- name: Check if site conf files exist
  stat:
    path: "{{ nginx_conf_dir }}/sites-enabled/{{ item.key }}"
  with_dict: "{{ nginx_sites }}"
  register: st
  failed_when: st.stat.exists != True

- name: Check if site conf files exist
  stat:
    path: /etc/nginx/htpasswd
  register: st
  failed_when: st.stat.exists != True
  when: nginx_basic_auth_pass != "" and nginx_basic_auth_user != ""

- name: Check if letsencrypt conf exists
  stat:
    path: "{{ nginx_conf_dir }}/snippets/letsencrypt.conf"
  register: st
  failed_when: st.stat.exists != True
  when: nginx_ssl_enable

- name: Check if nginx is running
  uri:
    url: http://localhost/
    validate_certs: "{{ molecule_ssl_validate | default(omit) }}"