---
- name: check and start nginx
  command: "nginx -t -c {{ nginx_conf_dir }}/nginx.conf"
  changed_when: false
  notify: restart nginx

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart metrics service
  systemd:
    daemon_reload: yes
    name: nginx_exporter
    state: restarted
  notify: check if nginx is serving metrics

- name: check if nginx is serving metrics
  uri:
    url: http://localhost:{{ nginx_status_port }}/nginx_status
