---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart metrics service
  systemd:
    daemon_reload: yes
    name: nginx_exporter
    state: restarted
